[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "14.x"
  NPM_FLAGS = "--legacy-peer-deps"  # If you need to handle peer dependency issues