services:
  - type: web
    name: my-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    rewrites:
      - source: /((?!static|favicon.ico).*)
        destination: /index.html
